version: "3"
services:
  app:
    image: db-exemplar
  db:
    image: mysql/mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: "12345678"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "12345678"
      MYSQL_DATABASE: "library"
    ports:
      - "3306:3306"
